### PR TITLE
[Typescript] Upgrade some dependencies + fix and build options

### PR DESCRIPTION
**Pull request by ewc340**
- [x] Add Typescript build options
- [x] Change package.json commands for `yarn start` and `yarn build`
- [x] Add back deprecated protobufs for now
- [x] Convert all files in codebase from `.js` extension to `.ts`

### CODE REVIEW

**Comment by ewc340** [comment]
@HaileyJang Can you try duplicating the js files and converting them to ts files, and then run `yarn build` to see if that works?

**Comment by HaileyJang** [comment]
Do you know why I am getting `syntax of the command is incorrect` when I run `yarn build`? I attempted to duplicate all the remaining js files and convert into ts inside the dawn folder and I am getting heck ton of errors + the syntax error above so it's not building.

**Comment by ewc340** [comment]
@HaileyJang Can you try pushing the change with converting everything to ts files on this branch?

**Comment by HaileyJang** [comment]
I am not sure if this is the way you wanted, but I converted all the js to files to ts. I separated out the process to multiple commits so you can revert back to whenever changes I made. I'm pretty sure there's going to be a lot of errors but we'll see what happens o.o

**Comment by ewc340** [comment]
> @ewc340 I am not sure if this is the way you wanted, but I converted all the js to files to ts. I separated out the process to multiple commits so you can revert back to whenever changes I made. I'm pretty sure there's going to be a lot of errors but we'll see what happens o.o

Ok thanks! I'll take a look at the errors and see what happens ;)

**Comment by ewc340** [comment]
@HaileyJang So there are actual multiple problems:
1. In order to use the JSX syntax (kinda like JS + HTML syntax) in the components, the file extension has to be `.tsx` instead of `.ts`. This wouldn't be needed in the actions or reducers since we're not rendering any visual components in there.
2. Since we are using typescript now, the syntax errors come from not defining the types for components that use `this.state` and `this.props` (which is basically all of them). For this, since there are lots of types to add and this PR is getting sorta big, I think it would be best to hold off on declaring types for the components for now, and we'll quickly come back to it once the actions and reducers are done (which should be very soon).

**Comment by ewc340** [comment]
@HaileyJang Sorry was a little bit busy the last few days, but one way we can test the refactored actions and reducers is to write tests for them, which I think there are some examples already. As for this PR, I think it is mostly done (minus the broken build on the components), but we also need to add some lint rules (which help enforce some code standards on the codebase). Currently we are using eslint, and there is also tslint (which is now deprecated since 2019), but I think we can stick with eslint. Can you take a look at how we can integrate Typescript with eslint?

**Pull request merged**
